name: Backend Deploy to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from main branch
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      # 3. Handle naming for GHCR
      - name: Lowercase the repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
   

      # Deploy to EC2 via SSH
      - name: Deploy Backend to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: REPO_LC 
          script: |
            echo "🚀 Starting Deployment..."

            # 1. Login to GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 2. Navigate to project and update docker-compose file
            cd ${{ secrets.EC2_PROJECT_PATH }}
            git pull origin main
            
            # 3. Pull the PRE-BUILT image from GHCR
            # This is much faster than building!
            docker pull ghcr.io/${{ env.REPO_LC }}/backend:latest 
            
            # 4. Restart the service using the new image
            # We export the variable so docker-compose.yml can see it
            export BACKEND_IMAGE="ghcr.io/${{ env.REPO_LC }}/backend:latest"
            docker-compose up -d backend
            
            # 5. Clean up old images to save disk space
            docker image prune -f           
            
            echo "✅ Backend deployment completed successfully!"